// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';
import {clipboard} from '../models';

export function CheckForUpdates(arg1:string):Promise<main.UpdateCheckResult>;

export function ClearAll():Promise<storage.ClearResult>;

export function CopyAndPaste(arg1:number):Promise<void>;

export function CopyToClipboard(arg1:number):Promise<void>;

export function DeleteClip(arg1:number):Promise<void>;

export function DownloadUpdatePackage(arg1:string,arg2:string):Promise<main.UpdateDownloadResult>;

export function ExportBackup():Promise<storage.BackupStats>;

export function ExportClip(arg1:number):Promise<main.ClipExportResult>;

export function ExportDiagnostics():Promise<main.DiagnosticStats>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetClipDetails(arg1:number):Promise<clipboard.ClipEntry>;

export function GetClipPage(arg1:number,arg2:number):Promise<main.ClipPage>;

export function GetClipPageByType(arg1:string,arg2:number,arg3:number):Promise<main.ClipPage>;

export function GetClipPageByTypeAndTag(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ClipPage>;

export function GetClipTags(arg1:string,arg2:string):Promise<Array<main.ClipTag>>;

export function GetClips(arg1:number,arg2:number):Promise<Array<clipboard.ClipEntry>>;

export function GetHotkeySettings():Promise<main.HotkeyConfig>;

export function GetImageDataURL(arg1:number):Promise<string>;

export function GetLastTargetInfo():Promise<main.TargetWindowInfo>;

export function GetStorageStats():Promise<storage.Stats>;

export function GetWindowPinned():Promise<boolean>;

export function HideWindow():Promise<void>;

export function ImportBackup():Promise<storage.BackupStats>;

export function OpenDataDir():Promise<void>;

export function QuitApp():Promise<void>;

export function RunAutoBackupNow():Promise<storage.BackupStats>;

export function RunCleanupNow():Promise<storage.Stats>;

export function RunStorageMaintenance():Promise<storage.MaintenanceResult>;

export function SearchClipPage(arg1:string,arg2:number,arg3:number):Promise<main.ClipPage>;

export function SearchClipPageByType(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ClipPage>;

export function SearchClipPageByTypeAndTag(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.ClipPage>;

export function SearchClips(arg1:string):Promise<Array<clipboard.ClipEntry>>;

export function SelectAutoBackupDir():Promise<string>;

export function TogglePin(arg1:number):Promise<void>;

export function ToggleWindowPin():Promise<boolean>;

export function UpdateAppSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function UpdateClipMetadata(arg1:number,arg2:string,arg3:string):Promise<clipboard.ClipEntry>;

export function UpdateHotkey(arg1:number,arg2:number):Promise<void>;
