// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function ClearAll() {
  return window['go']['main']['App']['ClearAll']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteClip(arg1) {
  return window['go']['main']['App']['DeleteClip'](arg1);
}

export function DownloadUpdatePackage(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdatePackage'](arg1, arg2);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportClip(arg1) {
  return window['go']['main']['App']['ExportClip'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetClipDetails(arg1) {
  return window['go']['main']['App']['GetClipDetails'](arg1);
}

export function GetClipPage(arg1, arg2) {
  return window['go']['main']['App']['GetClipPage'](arg1, arg2);
}

export function GetClipPageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClipPageByType'](arg1, arg2, arg3);
}

export function GetClipPageByTypeAndTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetClipPageByTypeAndTag'](arg1, arg2, arg3, arg4);
}

export function GetClipTags(arg1, arg2) {
  return window['go']['main']['App']['GetClipTags'](arg1, arg2);
}

export function GetClips(arg1, arg2) {
  return window['go']['main']['App']['GetClips'](arg1, arg2);
}

export function GetHotkeySettings() {
  return window['go']['main']['App']['GetHotkeySettings']();
}

export function GetImageDataURL(arg1) {
  return window['go']['main']['App']['GetImageDataURL'](arg1);
}

export function GetLastTargetInfo() {
  return window['go']['main']['App']['GetLastTargetInfo']();
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetWindowPinned() {
  return window['go']['main']['App']['GetWindowPinned']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RunAutoBackupNow() {
  return window['go']['main']['App']['RunAutoBackupNow']();
}

export function RunCleanupNow() {
  return window['go']['main']['App']['RunCleanupNow']();
}

export function RunStorageMaintenance() {
  return window['go']['main']['App']['RunStorageMaintenance']();
}

export function SearchClipPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchClipPage'](arg1, arg2, arg3);
}

export function SearchClipPageByType(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchClipPageByType'](arg1, arg2, arg3, arg4);
}

export function SearchClipPageByTypeAndTag(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchClipPageByTypeAndTag'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchClips(arg1) {
  return window['go']['main']['App']['SearchClips'](arg1);
}

export function SelectAutoBackupDir() {
  return window['go']['main']['App']['SelectAutoBackupDir']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function ToggleWindowPin() {
  return window['go']['main']['App']['ToggleWindowPin']();
}

export function UpdateAppSettings(arg1) {
  return window['go']['main']['App']['UpdateAppSettings'](arg1);
}

export function UpdateClipMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateClipMetadata'](arg1, arg2, arg3);
}

export function UpdateHotkey(arg1, arg2) {
  return window['go']['main']['App']['UpdateHotkey'](arg1, arg2);
}
